package by.bsuir.football.entity.enums;

public enum Formation {
    FOUR_THREE_THREE, FOUR_FOUR_TWO, FOUR_FOUR_ONE_ONE, FOUR_TWO_THREE_ONE,
    FOUR_THREE_ONE_TWO, FOUR_THREE_TWO_ONE, FIVE_THREE_TWO, THREE_FIVE_TWO,
    THREE_THREE_THREE_ONE, FIVE_FOUR_ONE, THREE_FOUR_THREE, FOUR_TWO_TWO_TWO,
    FOUR_ONE_TWO_ONE_TWO, FOUR_TWO_ONE_THREE
}
