package by.bsuir.football.entity.enums;

public enum Status {
    NOT_STARTED, IN_PLAY, UPDATE_LATER, ENDED, POSTPONED, CANCELLED, ABANDONED, INTERRUPTED,
    SUSPENDED, AWARDED, DELAYED, HALF_TIME, EXTRA_TIME, PENALTIES, BREAK_TIME, AWARDING,
    TO_BE_ANNOUNCED, AFTER_PENALTIES, AFTER_EXTRA_TIME
}
